package pl.norbit.gameserver.enums;

public enum Channel {
    CREATE_NEW_ROOM, JOIN_TO_ROOM, KICK, TIME_QUESTION_OUT, TIMER, QUESTION, END_GAME, SET_NICK, START_GAME,
    UPDATE_LOBBY, EXIT_GAME, LEAVE_ROOM
}
